# ------------------- Brownfield Airlines Deployment ------------------- #

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zuul-proxy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: zuul-proxy
  template:
    metadata:
      name: zuul-proxy
      labels:
        app: zuul-proxy
    spec:
      containers:
      - name: zuul-proxy
        image: navkkrnair/kube-zuul-proxy:1.0
        env:
        - name: CONFIG_SERVER
          value: "config-server"

---
# ------------------- Brownfield Airlines Service ------------------- #

apiVersion: v1
kind: Service
metadata:
  name: zuulproxy
spec:
  type: LoadBalancer
  selector:
    app: zuul-proxy
  ports:
  - port: 8080
    targetPort: 8080
  