apiVersion: v1
kind: ReplicationController
metadata:
   name: hostnameapp-rc
spec:
   replicas: 2
   selector:
      app: hostnameapp
   template:
      metadata:
         labels:
            app: hostnameapp
      spec:
         containers:
         - image: navkkrnair/hostnameapp:latest
           name: hostnameapp
           ports:
           - containerPort: 8080
             protocol: TCP
           